Problem Statement : Hospital Patient Data Analysis

Context:

A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.

Tasks:

1.	Load the patient dataset and show summary with info().
  
3.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
  
5.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

  
7.	Use groupby to find total bill amount per department.

  
9.	Remove duplicate patient records based on PatientID.

   
11.	Fill missing BillAmount values with the mean bill amount.

   
13.	Merge the billing dataset with patient dataset on PatientID.

   
15.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

   
17.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

   
Expected Outcome:


•	Final cleaned dataset with accurate billing info.

•	All missing values handled, merged dataset across PatientID.

•	Ability to perform further analytics on department-wise revenue or doctor performance.

In [1]:
import pandas as pd

In [2]:
patient_df=pd.read_csv(r"C:\Users\Sami\Downloads\Patient_Data.csv")
billing_df=pd.read_csv(r"C:\Users\Sami\Downloads\Billing_Data.csv")

In [3]:
patient_df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [4]:
billing_df.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [5]:
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [6]:
bill=patient_df[['PatientID', 'Department', 'Doctor', 'BillAmount']]
bill

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [7]:
patient_df = patient_df.drop(['ReceptionistID', 'CheckInTime'], axis=1)

print(patient_df.head())

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [9]:
dep_bill=patient_df.groupby('Department')['BillAmount'].sum()
dep_bill

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [10]:
patient_df=patient_df.drop_duplicates(subset='PatientID')
patient_df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [12]:
mean_bill=patient_df['BillAmount'].mean()
patient_df['BillAmount'].fillna(mean_bill)

0    5000.000000
1    6233.333333
2    7500.000000
3    6200.000000
4    6233.333333
Name: BillAmount, dtype: float64

In [14]:
merged_df = pd.merge(patient_df, billing_df, on='PatientID')
merged_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [20]:
new_patients = pd.DataFrame({
    'PatientID': [106, 107],
    'Name':['Kavee','Sriman'],
    'Department': ['Cardiology', 'Orthopedics'],
    'Doctor': ['Dr. John', 'Dr. Lee'],
    'BillAmount': [4500, 3800]
})
new_patients

   PatientID    Name   Department    Doctor  BillAmount
0        106   Kavee   Cardiology  Dr. John        4500
1        107  Sriman  Orthopedics   Dr. Lee        3800

In [21]:
new_patients_df = pd.DataFrame(new_patients)
merged_df = pd.concat([patient_df,new_patients_df],axis=0,ignore_index=True)
merged_df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        106    Kavee   Cardiology   Dr. John  4500.000000
6        107   Sriman  Orthopedics    Dr. Lee  3800.000000

In [22]:
merged_final_df = pd.concat([merged_df, billing_df[['InsuranceCovered', 'FinalAmount']]], axis=1)
merged_final_df['InsuranceCovered'] = merged_final_df['InsuranceCovered'].fillna(merged_final_df['InsuranceCovered'].mean())
merged_final_df['FinalAmount'] = merged_final_df['FinalAmount'].fillna(merged_final_df['FinalAmount'].mean())
merged_final_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,6233.333333,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.000000,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000.0,4000.0
5,106,Kavee,Cardiology,Dr. John,4500.000000,2000.0,3740.0
6,107,Sriman,Orthopedics,Dr. Lee,3800.000000,2000.0,3740.0

Outcome

Final cleaned dataset with accurate billing info.

All missing values handled, merged dataset across PatientID.

Ability to perform further analytics on department-wise revenue or doctor performance.